// Automatically generated by astro-icon
// 99c12f7ffffb43d63d0d5a38ff9985c4e058ecbf9af99a7f7de09d91f29c4733

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "astro"
		| "react"
		| "solidjs"
		| "star"
		| "svelte"
		| "vuejs";
}